---
title: "Lab01_Homework_RMarkdown"
author: "你是誰 R09342000 新聞所碩五"
date: "2021/02/22"
output:
  html_document:
    number_sections: no
    theme: united
    highlight: tango
    toc: yes
    toc_float:
      collapsed: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results = 'hold', comment = '#>', error = TRUE)
```

## 學習指引：Markdown 語法學習

RMarkdown 是一種檔案類型，使用者可以在 R 當中交替使用 Markdown 內文以及 R 的程式碼，並以此產出各種格式的報告，譬如 hmtl, word, PDF, PPT 等，用途很廣。

因此，這份作業希望能夠讓你熟習於撰寫 Markdown 語法，希望你能夠成為 Markdown 界的霸主，聽起來很厲害。

請參考網路上的教學，譬如這份中文的 [Markdown Cheatsheet 中文版](https://gist.github.com/billy3321/1001749662c370887c63bb30f26c9e6e)，或是這份中文的 [Gitbook 語法
](https://cowmanchiang.me/gitbook/gitbook/contents/how.html)。若你習慣看英文，或是想練習英文，不妨參考 [Mastering Markdown](https://guides.github.com/features/mastering-markdown/)，以及 RStudio 寫的 [Pandoc Markdown
](https://rmarkdown.rstudio.com/authoring_pandoc_markdown.html)

你可以選擇仔細練習每個部份，或是有問題的時候再去查找上面的資源。緊接著就要開始寫作業了，真是令人興奮！

## 作業: RMarkdown 語法練習

滿分共 100 分。

### A. 資料新聞案例舉例 (60 分) 

請找一則資料新聞，並以 Markdown 語法介紹它，介紹文必須包含底下者三種元素：字體加深, 清單(lists), 連結(links)，此外請你再額外挑選至少兩種元素，譬如說字體變斜, 插入圖片, 加入引用, etc.  請至少產出兩個段落（因此換行很重要），但字數不用多，250字-400字即可，重點是使用 Markdown 語法。

你可以點擊 RStudio 上方的 Knit 按鈕輸出檔案並且預覽，也可以利用
 [Markdown 線上編輯器](https://jbt.github.io/markdown-editor)看你的結果長得如何。請把結果貼在`#### 結果`下方。
 
#### 結果

### B. R code chunk 練習 (40 分) 

#### B.01 (20分)

如先前所提，Rmarkdown 當中可以插入 code chunk，請參考 [RStudio 的教學](https://rmarkdown.rstudio.com/lesson-3.html)，在底下插入一段 code chunk，並在當中計算 1+1 的答案並將結果列印出來。

#### B.02 (20分)
- 請解釋 chunk header 中參數 include = FALSE 會有什麼後果，並在底下加一段 include = FALSE 的 code chunk，一樣在裡面計算 1+1 的答案。

- 請解釋 chunk header 中參數 echo = FALSE 會有什麼後果，並在底下加一段 echo = FALSE 的 code chunk，一樣在裡面計算 1+1 的答案。


